
name: ci

on:
  push:
  pull_request:

jobs:
  backend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Smoke test
        run: |
          python - <<'PY'
from fastapi import FastAPI
print("FastAPI import ok")
PY
